# Generated by Django 2.2 on 2023-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=128, verbose_name='名称')),
                ('fileSize', models.IntegerField(verbose_name='大小')),
                ('fileCreateDate', models.DateTimeField(db_column='buildTime', verbose_name='创建时间')),
                ('headImg', models.FileField(upload_to='./upload/')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
            },
        ),
    ]
