# Generated by Django 2.2 on 2023-05-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='fileCreateDate',
            field=models.DateTimeField(auto_now_add=True, db_column='buildTime', verbose_name='创建时间'),
        ),
    ]
