# Generated by Django 2.2 on 2023-05-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_entry_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
    ]
